name: ğŸš€ Deploy Traefik-proxy to VPS 

on:
  push:
    branches:
      - main  # Pas aan indien je een andere branch gebruikt

jobs:
  deploy:
    name: ğŸ³ Deploy stack
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v3

    - name: ğŸ” Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: ğŸš€ Deploy Docker Stack to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOF
          cd ~/traefik  # Verander dit naar de juiste map op je VPS
          git pull origin main
          docker stack deploy -c docker-compose.yml ${{ secrets.STACK_NAME }}
